### PR TITLE
add PySide(python27) and PyQt5(python3) examples

### PR DESCRIPTION
**Pull request by mackst**

### CODE REVIEW

**Comment by realitix** [comment]
Whaaa! Amazing pull request! I'm testing it !

**Comment by realitix** [comment]
I tested it and I saw that your examples only support Windows.
I work only on Linux, can you add Linux support ? (When creating the surface)

**Comment by mackst** [comment]
I don't have a Linux system.
I can try this https://msdn.microsoft.com/en-us/commandline/wsl/install_guide.

**Comment by realitix** [comment]
It can't work with Linux subsystem on windows because you need X server.
I can do it, just let me some time.

**Comment by realitix** [comment]
Hello @mackst, I'm trying to add Linux support (it's just about using `vkCreateXlibSurfaceKHR` for the surface) but I don't know how to get the X11 `display` and `window`. Do you know where I can get theses pointers ?

**Comment by mackst** [comment]
You can try QX11Info class. It only available on X11.

QX11Info.display()
http://doc.qt.io/qt-5/qx11info.html

**Comment by mackst** [comment]
The window should be able to use self.winId(). This function return a address on Linux.

**Comment by realitix** [comment]
Sadly, I struggle to make it works on linux with XCB surface :disappointed:

**Comment by mackst** [comment]
@realitix I add a new glfw example. Can you test it on Linux?
I can't help with PySide and PyQt5 on Linux. Qt 5.10 will have vulkan support. PyQt5 should also have it supported. I will look into it when it release. But PyQt5 is python 3 only.

**Comment by realitix** [comment]
Thanks @mackst. I will test it as soon as possible! I'm traveling in Australia right now for pycon Australia ;-)

**Comment by mackst** [comment]
Hi @realitix I added Linux support for the PyQt5 example. I did it on the VM. It failed on pick a GPU because there is no GPU. But the surface creation was successful. Can you test it?

**Comment by realitix** [comment]
Hi @mackst, don't worry I don't forget ;-) 
I am on holiday in Australia, that's why I can't try it currently. I come back home in 1 week, I let you know! Thanks again.

**Comment by realitix** [comment]
Hi @mackst !
I have merged it manually, you can see it in the commit log.

Thanks a lot for this great contribution !!

**Pull request closed without merging**
